# A scrape configuration scraping a Node Exporter and the Prometheus server
# itself.
scrape_configs:
  # Scrape Prometheus itself every 60 seconds.
  - job_name: 'prometheus'
    scrape_interval: 60s
    static_configs:
     - targets: ['localhost:9090']

# Scrape the Node Exporter every 60 seconds.
  - job_name: 'node'
    scrape_interval: 60s
    static_configs:
     - targets: ['<ip_host/dns_name_host>:9100','<ip_host/dns_name_host>:9100']

# Postgres exporter request every 60s
  - job_name: 'pg'
    scrape_interval: 60s
    static_configs:
    - targets: ['<ip_host_with_postgres/dns_name_host_with_postgres>:9187']
