# A scrape configuration scraping a Node Exporter and the Prometheus server
# itself.
scrape_configs:
  # Scrape Prometheus itself every 60 seconds.
  - job_name: 'prometheus'
    scrape_interval: 60s
    static_configs:
     - targets: ['localhost:9090']

# Scrape the Node Exporter every 60 seconds.
  - job_name: 'node'
    scrape_interval: 60s
    static_configs:
     - targets: ['10.8.26.248:9100','10.8.26.249:9100']

# Postgres exporter request every 60s
  - job_name: 'pg'
    scrape_interval: 60s
    static_configs:
    - targets: ['10.8.26.248:9187']
